### ISSUE TITLE
v0.3 roadmap

### ISSUE THREAD

**Issue by milesj** [moonrepo/moon#128]
Cool things to look forward to!

- [x] Support a list of globs in `.moon/workspace.yml` `projects` instead of a map. This will automatically find projects when `moon` is ran.
- [x] Move the `project.yml` `project.type` field to the root of the document, so that it can be defined by itself.
- [x] Add a `language` setting to `project.yml`.
- [x] Improve handling of colored output. It seems to work well in yarn, but has issues in npm. Unsure about pnpm.
- [x] Better code coverage and more integration tests.
