### ISSUE TITLE
v0.5 roadmap

### ISSUE THREAD

**Issue by milesj** [moonrepo/moon#157]
- [x] Only load project configs (`package.json`, `tsconfig.json`) once instead of re-reading the file constantly. This will require sharing the struct across threads using `Arc<RwLock<OnceCell>>>`.
- [x] Verify if we can use YAML references. Support is dependent on `serde_yaml`.
- [x] https://github.com/moonrepo/moon/issues/147
- [x] Rework `config` crate error handling. Instead of doing figment -> validator, we should do the reverse.
- [x] Cache VCS (`git`) commands.
- [x] Detect VCS settings during `moon init`.
- [x] Increase code coverage and add more integration tests.
