### ISSUE TITLE
v0.6 roadmap

### ISSUE THREAD

**Issue by milesj** [moonrepo/moon#169]
- [x] Automatically create a `tsconfig.json` when syncing project references and the file is missing.
- [x] Add Chrome profiling to spawned Node.js processes.
- [x] Add a `@group()` token that copies file group values as-is.
- [x] Start on a `moon query` CLI command.
