### ISSUE TITLE
v0.7 roadmap

### ISSUE THREAD

**Issue by milesj** [moonrepo/moon#185]
- [x] Add `$projectType`, `$taskType`, and `$language` tokens.
- [x] Add `actionRunner.implicitInputs` to `.moon/workspace.yml`. These inputs are then inherited by _all_ tasks automatically.
- [x] Add `--type` and `--language` filters to `moon query projects`.
- [x] Add `moon dep-graph` command.
- [x] Expand docs with FAQs

## Investigate

- [x] Refactor our project graph to pass around `Project` references instead of cloning.
