### ISSUE TITLE
v0.8 roadmap

### ISSUE THREAD

**Issue by milesj** [moonrepo/moon#201]
This release will focus heavily on Node.js interoperability, primarily around `package.json` integration.

- [x] Add a special `noop` task (necessary for other features).
- [x] Add a `moon migrate from-package-json` command that will:
  - [x] Migrate `package.json` scripts to `project.yml` tasks.
  - [x] Migrate `package.json` dependencies (for local workspace linked packages) to `project.yml` `dependsOn`.
- [x] Add a `moon sync` command that syncs the entire repository to a healthy state.
- [x] Add a `node.inferTasksFromPackageScripts` setting that will infer and create `project.yml` tasks from `package.json` scripts.
