### ISSUE TITLE
v0.9 roadmap

### ISSUE THREAD

**Issue by milesj** [moonrepo/moon#211]
- [x] Add type to `dependsOn`, to differentiate between development and production deps.
- [x] Support different dependency version types: `workspace:*`, `link:`, `file:`, `*`, etc.
- [x] Support env vars as task inputs.
- [x] Add a `cache` option to tasks.
- [x] Handle all pnpm edge cases (different linker patterns).

## Internals

- [x] Clean up our fixtures usage/utils.

## Breaking

- [ ] Rename `tasks[].type`? Maybe `platform`? Or `runtime`?
