### ISSUE TITLE
v0.10 roadmap

### ISSUE THREAD

**Issue by milesj** [moonrepo/moon#235]
- [x] https://github.com/moonrepo/moon/issues/228
- [x] https://github.com/moonrepo/moon/issues/207
- [x] Support project aliases? Look into ways to use a `package.json` name.
  - [x] Support `/` and `@` in IDs?
- [x] Infer `tasks.*.type` based on the command. Do our best to detect "system".
- [x] Refactor hash cache to use `.tar` files instead of copying entire folders.
- [x] Update default tool versions.
