### ISSUE TITLE
v0.11 roadmap

### ISSUE THREAD

**Issue by milesj** [moonrepo/moon#248]
- [x] Add an `envFile` option to tasks.
- [x] Add an "is long running" option to tasks.
- [x] Add more output styles.
- [x] Update `moon run` to support multiple targets.
- [x] Add `moon clean` and other utils for cleaning up stale cache.
- [x] TS v.4.8 compatibility
- [x] Rust v1.63
