### ISSUE TITLE
v0.12 roadmap

### ISSUE THREAD

**Issue by milesj** [moonrepo/moon#265]
- [x] https://github.com/moonrepo/moon/issues/229
- [x] Add Linux arm64 support
- [x] Add a CI report/manifest
- [x] Add affected support to `moon query projects`
- [x] Make `typescript` setting optional
- [x] Integrate Astro build
- [x] Investigate a GitHub bot/app/action
- [x] Finalize eslint/jest/etc packages
