### ISSUE TITLE
v0.13 roadmap

### ISSUE THREAD

**Issue by milesj** [moonrepo/moon#280]
- [x] Add `moon check` command
- [x] Use versions from lockfile instead of `package.json` for hashing
- [x] Split `SetupToolchain` action to be language/platform specific
- [x] Error if an output is defined but it was not created
- [x] Add types package
- [x] Add astro command checks
- [x] Rename `actionRunner` to `runner`
