### ISSUE TITLE
v0.14 roadmap

### ISSUE THREAD

**Issue by milesj** [moonrepo/moon#296]
Small roadmap but they're all large features!

- [x] Add template generator / scaffolding
- [x] Implement project graph implicit dependency scanning
- [x] Integrate GitHub action for run reports
- [x] Avoid caching and hashing in Docker
