### ISSUE TITLE
v0.15 roadmap

### ISSUE THREAD

**Issue by milesj** [moonrepo/moon#313]
- [x] Add `moon docker scaffold` command to create the repo skeleton for `COPY`.
- [x] Add `moon docker prune` command to prune the repo when in a docker container/image.
- [x] Implement event emitter in workspace and action runner.
- [x] Update toolchain to support arbitrary tool + version combos. This unlocks different versions per project.
- [x] Support template file frontmatter.
