### ISSUE TITLE
v0.16 roadmap

### ISSUE THREAD

**Issue by milesj** [moonrepo/moon#334]
- [x] TypeScript - Add a `routeOutDirToCache` setting.
- [x] TypeScript - Add a `syncDependenciesAsPaths` setting: https://github.com/moonrepo/moon/issues/319
- [x] Support project-level tool version overrides (`workspace.node.version`).
- [x] Add `runner.implicitDeps`.
- [x] Support file extensions (like `.tpl` or `.tera`) for template files.
