### ISSUE TITLE
v0.17 roadmap

### ISSUE THREAD

**Issue by milesj** [moonrepo/moon#356]
- [x] BREAKING: Rename task `type` to `platform`
- [x] Support extended yaml: https://github.com/moonrepo/moon/issues/164
- [x] Add webhooks support to events
- [x] Support an object form for generator enum values
- [x] Shorthand "self" targets
- [x] Create JSON schema for `template.yml`
- [x] Node.js v18/19 support
- [x] Add `--report` to `moon check`

### Internal

- [x] Start on infra for vscode extension
