### ISSUE TITLE
v0.18 roadmap

### ISSUE THREAD

**Issue by milesj** [moonrepo/moon#379]
- [x] Add benchmarking system
- [x] Enable inlining: https://github.com/moonrepo/moon/issues/144
- [x] Add `node.runArgs` setting, to pass args to the running `node` (`node.exe`) binary
- [x] Recursively cache `extends` field in configs
- [x] Separate project globs from map
- [x] Improve `moon init` by handling more node options
- [x] More platformication of internals
- [x] Write stdout/err log files for each target in CI
- [x] Bump default tool version
- [x] npm 9 support
