### ISSUE TITLE
v0.19 roadmap

### ISSUE THREAD

**Issue by milesj** [moonrepo/moon#405]
- [x] Lay the foundation for remote caching
- [x] Improve the dependency graph
- [x] Support `.editorconfig` when writing json/yam files: https://github.com/moonrepo/moon/issues/397
- [x] Use `FxHashMap` for performance: https://nnethercote.github.io/perf-book/hashing.html
- [x] Handle conflicts/merging for template files: https://github.com/moonrepo/moon/issues/310
- [x] Add a "ci provider" layer
