### ISSUE TITLE
v0.21 roadmap

### ISSUE THREAD

**Issue by milesj** [moonrepo/moon#479]
- [x] Support multiple `--status` options: https://github.com/moonrepo/moon/issues/455
- [x] Update `affectedFiles` to support "env" or "args" enum
- [x] Land the graph visualizer 
- [x] Add `moon run --force` to bypass caches
- [x] Add `moon init --minimal` for a quick setup
- [x] Implement partial language support (outside of toolchain)
- [x] Support new langs: go, deno, ruby, rust, php, python

### Internal

- [x] Implement a new project graph. Custom DAG instead of petgraph.
- [x] Add version detection based on cwd to toolchain.
- [x] Hard-code CLI global lookups.
- [x] Change all fs operations to sync.
