### ISSUE TITLE
v0.22 roadmap

### ISSUE THREAD

**Issue by milesj** [moonrepo/moon#513]
- [x] Add moon version constraint to `.moon/workspace.yml`
- [x] Implement new action pipeline to improve upon the current runner shortcomings
  - [x] Add concurrency: https://github.com/moonrepo/moon/issues/477
- [x] Rework hashing to be generic and useful for anything
  - [x] Project graph cache
  - [x] Install deps cache
- [x] Make `project` fields optional: https://github.com/moonrepo/moon/issues/524
- [x] Add migrate from turborepo commands
- [x] Rename upstream to remote
- [x] Add Bun language to Tier 1
- [x] Refactor `docker` commands for other languages

### Proto
- [x] Create shims and update toolchain to use them
- [x] Implement concept of local/global/shell version locking

**Comment by itsezc** [comment]
Could we add #520 to the milestone, thanks!
