### ISSUE TITLE
v0.23 roadmap

### ISSUE THREAD

**Issue by milesj** [moonrepo/moon#557]
- [x] BREAKING: Rename `.moon/project.yml` to `.moon/tasks.yml`.
- [x] BREAKING: Move `implicitDeps` and `implicitInputs` to `.moon/tasks.yml`.
- [x] Support project-level env vars: https://github.com/moonrepo/moon/issues/489
- [x] Support globs in outputs.

### Internal

- [x] Import proto from a single crate.
- [x] Proto: Add `list`, `list-remote` commands.
- [x] Proto: Implement global shims.
