### ISSUE TITLE
v0.24 roadmap

### ISSUE THREAD

**Issue by milesj** [moonrepo/moon#580]
- [x] Add new `moon query tasks` command.
- [x] Add a project-level `platform` setting in `moon.yml`.
- [x] Support TypeScript v5.
- [x] Support tokens in `outputs`: https://github.com/moonrepo/moon/issues/401

### Internal

- [x] proto: Add `bin`, `local`, `global` commands.
- [x] proto: Investigate shell completions.
- [x] Hook up CI runs to moonbase.
