### ISSUE TITLE
v0.25 roadmap

### ISSUE THREAD

**Issue by milesj** [moonrepo/moon#617]
- [x] Deno tier 2 language support.
- [x] Project-level TypeScript settings.
- [x] Offline mode.

### moonbase

- [x] Hook up CI insights. Capture more information.

### Internal

- [x] Move proto to a separate repository.
