### ISSUE TITLE
v0.26 roadmap

### ISSUE THREAD

**Issue by milesj** [moonrepo/moon#659]
- [x] Officially release proto and update moon to use it
- [ ] Add Deno npm/package support
- [ ] Add Deno tier 3 (maybe)
- [x] `moon docker setup` - https://github.com/moonrepo/moon/issues/625

**Comment by milesj** [comment]
Pushing Deno till the next release.
