### ISSUE TITLE
v1 roadmap

### ISSUE THREAD

**Issue by milesj** [moonrepo/moon#708]
It's happening!

- [x] Project constraints/boundaries via tagging
- [x] CI/CD provider information
- [x] Telemetry settings
- [x] `$timestamp` token - https://github.com/moonrepo/moon/issues/705

## Investigate

- [x] Wrap `system` commands in a shell
